### ISSUE TITLE
Use React.memo

### ISSUE THREAD

**Issue by finom** [ricokahler/hocify#17]
Would be cool is the library would wrap a returned component into React.memo so a component isn't going to be re-rendered if no props are changed.

**Comment by ricokahler** [comment]
Hi @finom !

I like the suggestion, however looking at other HOCs libs (in particular, `recompose`), it seems like the community prefers to wrap with `React.memo` themselves then have the libs do it by default — which makes sense because if all HOCs wrapped with `memo` then you'd potentially wrap it more than once.

You can wrap with memo yourself by chaining HOCs like so:

```js
import React, { Component, memo } from 'react';
import hocify from 'hocify';

function useHook() {/* ... */}
const withHoc = hocify(useHook);

class SomeComponent extends Component { /* ... */ }

export default withHoc(memo(SomeComponent));
```

---

Let me know if that works for you!

**Comment by finom** [comment]
@ricokahler thank you for the response. Yep, it makes sense. But I thought since everybody is slowly moving for recompose-like enhancers to hooks it would be cool to use hocify as the only enhancer without using `compose` from recompose or something like that at all. Maybe hocify should accept `{ memo: bool }` option as a second argument?

**Comment by ricokahler** [comment]
No, I think I still prefer composing the HOCs over adding the param.

```js
withHoc(memo(SomeComponent));
```

vs

```js
withHoc(SomeComponent, { memo: true });
```

The expression length is shorter and it works without having to add in a change. 😅

---

I'll close this for now but thanks for this!

Keep the feedback coming! ❤️
